environment:
  global:
        # can be "stable" or anything to be passed to "git checkout". In the
        # latter case, you MUST adjust VALIDATOR_EXECUTABLE to the following value:
        # "C:\\projects\\mne-bids\\bids-validator\\bids-validator\\bin\\bids-validator"
        # ... whereas for "stable", VALIDATOR_EXECUTABLE MUST be set to "n/a"
        VALIDATOR_VERSION: "347117838f2b929e"
        # can be any branch of EZTrack (e.g., "maint/0.18", "master", ...)
        MNE_VERSION: "master"
        VALIDATOR_EXECUTABLE: "C:\\projects\\eztrack\\bids-validator\\bids-validator\\bin\\bids-validator"
        NODEJS_VERSION: "10.16.1"
        PYTHON: "C:\\conda"
  matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        PYTHON_VERSION: "3.6"
        PYTHON_ARCH: "64"
        PYTHON_ROOT: "C:\\Miniconda36-x64"
        CONDA_INSTRUMENTATION_ENABLED: "true"

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/
  - ps: Update-NodeJsInstallation $env:NODEJS_VERSION
  - node --version
  - npm --version
  - yarn --version
  - cmd: if [%VALIDATOR_VERSION%]==[stable] (
      npm install -g bids-validator
      bids-validator --version
      which bids-validator
      ) else (
      git clone https://github.com/bids-standard/bids-validator &&
      cd bids-validator &&
      git checkout %VALIDATOR_VERSION% &&
      yarn &&
      cd .. &&
      set PATH="%PATH%;C:\projects\eztrack\bids-validator\bids-validator\bin\" )
  - CALL "%PYTHON_ROOT%\\Scripts\\activate.bat"
  - "conda env create -f environment.yml --name=testenv"
  - "conda activate testenv"
  - "conda config --add channels conda-forge"
  - 'conda config --add channels bioconda'
  - 'conda config --add channels aramislab'
  - 'conda install sphinx sphinx-gallery sphinx_bootstrap_theme numpydoc black pytest pytest-cov coverage codespell pydocstyle'
  - 'pip install coverage-badge anybadge'
  - 'pip install autoreject pyprep'
    # dev versions of mne-python, mne-bids
  - 'pip install --upgrade --no-deps https://api.github.com/repos/mne-tools/mne-python/zipball/master'
  - 'pip install --upgrade https://api.github.com/repos/mne-tools/mne-bids/zipball/master'
  - "python setup.py develop"
  - "python -c \"import eztrack;""

# cache pip unless appveyor.yml is changed
# https://stackoverflow.com/a/31496309/5201771
cache:
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'

build: false

test_script:
  - "pytest ./tests/ --verbose"
